### ISSUE TITLE
Support for BodyStyle = WebMessageBodyStyle.Wrapped in WebInvoke (post) methods

### ISSUE THREAD

**Issue by PhlashGBG** [abelsilva/swaggerwcf#26]
Hi Abel,

I think I've found a bug when using the WebMessageBodyStyle.Wrapped attribute on a WebInvoke method with multiple request parameters - the generated swagger path element contains multiple body parameters (illegal according to the specification) eg a method declared via an interface as:

```
        [WebInvoke(BodyStyle = WebMessageBodyStyle.Wrapped, RequestFormat = WebMessageFormat.Json, ResponseFormat = WebMessageFormat.Json)]
        [OperationContract]
        bool CheckCredentials(
            string AccountName,
            string Password);
```

produces the following swagger declaration:

```
        "/TestService/CheckCredentials": {
            "post": {
                "operationId": "TestService.CheckCredentials",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "parameters": [{
                    "name": "AccountName",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/System.String"
                    }
                },
                {
                    "name": "Password",
                    "in": "body",
                    "required": true,
                    "schema": {
                        "$ref": "#/definitions/System.String"
                    }
                }],
...
```

I think (according to the scant information I can find on MSDN / StackOverflow) WCF expects the Wrapped attribute to implicitly generate a new object containing the multiple parameters as named fields: http://stackoverflow.com/questions/20206069/restful-web-service-body-format

Cheers,
Phil.

**Comment by abelsilva** [comment]
Hi Phil

sorry for not replying before...

I'm not considering implementing this for now.
I understand the issue but I believe it will end up in a lot of work to implement this.

I'll keep the issue open til I change my mind or some picks it up :)

Cheers
Abel

**Comment by dhivyadk** [comment]
Any workaround or suggestion to handle this?

**Comment by abelsilva** [comment]
Maybe if you use body 'bare' and wrap your class in a main class?

Would it work for you?

**Comment by abelsilva** [comment]
This is implemented now, let me know if it is working for you

**Comment by dhivyadk** [comment]
Thank you so much! I will check and let you know if i face any issue!

**Comment by PhlashGBG** [comment]
Just tried pulling the latest source tree and re-integrating with my project to test this fix. Unfortunately I'm seeing a failure elsewhere (see below) so unable to report yet, will need to debug this exception first:

	31/10/2016 16:33:03	System.ArgumentException: Type provided must be an Enum.Parameter name: enumType
	   at System.RuntimeType.GetEnumNames()
	   at SwaggerWcf.Support.DefinitionsBuilder.ProcessProperty(PropertyInfo propertyInfo, IList\`1 hiddenTags, Stack\`1 typesStack) in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\Support\DefinitionsBuilder.cs:line 245
	   at SwaggerWcf.Support.DefinitionsBuilder.ProcessProperties(Type definitionType, DefinitionSchema schema, IList`1 hiddenTags, Stack`1 typesStack) in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\Support\DefinitionsBuilder.cs:line 122
	   at SwaggerWcf.Support.DefinitionsBuilder.ConvertTypeToDefinition(Type definitionType, IList\`1 hiddenTags, Stack\`1 typesStack) in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\Support\DefinitionsBuilder.cs:line 83
	   at SwaggerWcf.Support.DefinitionsBuilder.Process(IList\`1 hiddenTags, IList\`1 visibleTags, List\`1 definitionsTypes) in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\Support\DefinitionsBuilder.cs:line 31
	   at SwaggerWcf.Support.ServiceBuilder.BuildService() in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\Support\ServiceBuilder.cs:line 37
	   at SwaggerWcf.Support.ServiceBuilder.Build() in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\Support\ServiceBuilder.cs:line 17
	   at SwaggerWcf.SwaggerWcfEndpoint.Init() in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\SwaggerWcfEndpoint.cs:line 31
	   at SwaggerWcf.SwaggerWcfEndpoint..ctor() in Y:\tfs\VSTS\StarTrek-Trunk\Libraries\SwaggerWcf\SwaggerWcfEndpoint.cs:line 23

Please note that these line numbers may not match release 0.1.16 as I have a number of as-yet-unsubmitted patches that add security definition support and interface-specific overrides to the base SwaggerWcf tree.. I'll let you know here if I get past this point :)

**Comment by abelsilva** [comment]
can you check if your issue still applies?

**Comment by PhlashGBG** [comment]
Confirmed, v0.1.18 fixes this issue for me, many thanks, Phil.
